// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: proto/collector.proto

package gopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_collector_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{0}
}

type GrpcPingResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	IsTimeout bool   `protobuf:"varint,2,opt,name=IsTimeout,proto3" json:"IsTimeout,omitempty"`
	RttMicros uint32 `protobuf:"varint,3,opt,name=RttMicros,proto3" json:"RttMicros,omitempty"`
	SendAt    int64  `protobuf:"varint,4,opt,name=SendAt,proto3" json:"SendAt,omitempty"`
}

func (x *GrpcPingResult) Reset() {
	*x = GrpcPingResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_collector_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcPingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPingResult) ProtoMessage() {}

func (x *GrpcPingResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPingResult.ProtoReflect.Descriptor instead.
func (*GrpcPingResult) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{1}
}

func (x *GrpcPingResult) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *GrpcPingResult) GetIsTimeout() bool {
	if x != nil {
		return x.IsTimeout
	}
	return false
}

func (x *GrpcPingResult) GetRttMicros() uint32 {
	if x != nil {
		return x.RttMicros
	}
	return 0
}

func (x *GrpcPingResult) GetSendAt() int64 {
	if x != nil {
		return x.SendAt
	}
	return 0
}

type PingReportReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*GrpcPingResult `protobuf:"bytes,1,rep,name=Results,proto3" json:"Results,omitempty"`
	AgentID uint32            `protobuf:"varint,2,opt,name=AgentID,proto3" json:"AgentID,omitempty"`
}

func (x *PingReportReq) Reset() {
	*x = PingReportReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_collector_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingReportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReportReq) ProtoMessage() {}

func (x *PingReportReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReportReq.ProtoReflect.Descriptor instead.
func (*PingReportReq) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{2}
}

func (x *PingReportReq) GetResults() []*GrpcPingResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *PingReportReq) GetAgentID() uint32 {
	if x != nil {
		return x.AgentID
	}
	return 0
}

type GrpcTcpPingResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	IsTimeout bool   `protobuf:"varint,2,opt,name=IsTimeout,proto3" json:"IsTimeout,omitempty"`
	RttMicros uint32 `protobuf:"varint,3,opt,name=RttMicros,proto3" json:"RttMicros,omitempty"`
	SendAt    int64  `protobuf:"varint,4,opt,name=SendAt,proto3" json:"SendAt,omitempty"`
}

func (x *GrpcTcpPingResult) Reset() {
	*x = GrpcTcpPingResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_collector_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcTcpPingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcTcpPingResult) ProtoMessage() {}

func (x *GrpcTcpPingResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcTcpPingResult.ProtoReflect.Descriptor instead.
func (*GrpcTcpPingResult) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{3}
}

func (x *GrpcTcpPingResult) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *GrpcTcpPingResult) GetIsTimeout() bool {
	if x != nil {
		return x.IsTimeout
	}
	return false
}

func (x *GrpcTcpPingResult) GetRttMicros() uint32 {
	if x != nil {
		return x.RttMicros
	}
	return 0
}

func (x *GrpcTcpPingResult) GetSendAt() int64 {
	if x != nil {
		return x.SendAt
	}
	return 0
}

type TcpPingReportReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*GrpcTcpPingResult `protobuf:"bytes,1,rep,name=Results,proto3" json:"Results,omitempty"`
	AgentID uint32               `protobuf:"varint,2,opt,name=AgentID,proto3" json:"AgentID,omitempty"`
}

func (x *TcpPingReportReq) Reset() {
	*x = TcpPingReportReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_collector_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TcpPingReportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpPingReportReq) ProtoMessage() {}

func (x *TcpPingReportReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpPingReportReq.ProtoReflect.Descriptor instead.
func (*TcpPingReportReq) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{4}
}

func (x *TcpPingReportReq) GetResults() []*GrpcTcpPingResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *TcpPingReportReq) GetAgentID() uint32 {
	if x != nil {
		return x.AgentID
	}
	return 0
}

type GrpcFPingResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	IsTimeout bool   `protobuf:"varint,2,opt,name=IsTimeout,proto3" json:"IsTimeout,omitempty"`
	RttMicros uint32 `protobuf:"varint,3,opt,name=RttMicros,proto3" json:"RttMicros,omitempty"`
}

func (x *GrpcFPingResult) Reset() {
	*x = GrpcFPingResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_collector_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcFPingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcFPingResult) ProtoMessage() {}

func (x *GrpcFPingResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcFPingResult.ProtoReflect.Descriptor instead.
func (*GrpcFPingResult) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{5}
}

func (x *GrpcFPingResult) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *GrpcFPingResult) GetIsTimeout() bool {
	if x != nil {
		return x.IsTimeout
	}
	return false
}

func (x *GrpcFPingResult) GetRttMicros() uint32 {
	if x != nil {
		return x.RttMicros
	}
	return 0
}

type FPingReportReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*GrpcFPingResult `protobuf:"bytes,1,rep,name=Results,proto3" json:"Results,omitempty"`
	AgentID uint32             `protobuf:"varint,2,opt,name=AgentID,proto3" json:"AgentID,omitempty"`
}

func (x *FPingReportReq) Reset() {
	*x = FPingReportReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_collector_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FPingReportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FPingReportReq) ProtoMessage() {}

func (x *FPingReportReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FPingReportReq.ProtoReflect.Descriptor instead.
func (*FPingReportReq) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{6}
}

func (x *FPingReportReq) GetResults() []*GrpcFPingResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *FPingReportReq) GetAgentID() uint32 {
	if x != nil {
		return x.AgentID
	}
	return 0
}

type GrpcMTRResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hop       uint32 `protobuf:"varint,1,opt,name=Hop,proto3" json:"Hop,omitempty"`
	IP        string `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	IsTimeout bool   `protobuf:"varint,3,opt,name=IsTimeout,proto3" json:"IsTimeout,omitempty"`
	RttMicros uint32 `protobuf:"varint,4,opt,name=RttMicros,proto3" json:"RttMicros,omitempty"`
}

func (x *GrpcMTRResult) Reset() {
	*x = GrpcMTRResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_collector_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcMTRResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcMTRResult) ProtoMessage() {}

func (x *GrpcMTRResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcMTRResult.ProtoReflect.Descriptor instead.
func (*GrpcMTRResult) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{7}
}

func (x *GrpcMTRResult) GetHop() uint32 {
	if x != nil {
		return x.Hop
	}
	return 0
}

func (x *GrpcMTRResult) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *GrpcMTRResult) GetIsTimeout() bool {
	if x != nil {
		return x.IsTimeout
	}
	return false
}

func (x *GrpcMTRResult) GetRttMicros() uint32 {
	if x != nil {
		return x.RttMicros
	}
	return 0
}

type MTRReportReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*GrpcMTRResult `protobuf:"bytes,1,rep,name=Results,proto3" json:"Results,omitempty"`
	AgentID uint32           `protobuf:"varint,2,opt,name=AgentID,proto3" json:"AgentID,omitempty"`
}

func (x *MTRReportReq) Reset() {
	*x = MTRReportReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_collector_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MTRReportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MTRReportReq) ProtoMessage() {}

func (x *MTRReportReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MTRReportReq.ProtoReflect.Descriptor instead.
func (*MTRReportReq) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{8}
}

func (x *MTRReportReq) GetResults() []*GrpcMTRResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *MTRReportReq) GetAgentID() uint32 {
	if x != nil {
		return x.AgentID
	}
	return 0
}

var File_proto_collector_proto protoreflect.FileDescriptor

var file_proto_collector_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x74, 0x0a, 0x0e, 0x47, 0x72, 0x70, 0x63, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x49, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x52, 0x74, 0x74, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x52, 0x74, 0x74, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x53, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x22, 0x63, 0x0a, 0x0d, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x38, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x50, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x77, 0x0a, 0x11, 0x47,
	0x72, 0x70, 0x63, 0x54, 0x63, 0x70, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x1c, 0x0a, 0x09, 0x49, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x49, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x52, 0x74, 0x74, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x52, 0x74, 0x74, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x53, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x65,
	0x6e, 0x64, 0x41, 0x74, 0x22, 0x69, 0x0a, 0x10, 0x54, 0x63, 0x70, 0x50, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x3b, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x63, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x54,
	0x63, 0x70, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22,
	0x5d, 0x0a, 0x0f, 0x47, 0x72, 0x70, 0x63, 0x46, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x49, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x52, 0x74, 0x74, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x52, 0x74, 0x74, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x22, 0x65,
	0x0a, 0x0e, 0x46, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x39, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x46, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x6d, 0x0a, 0x0d, 0x47, 0x72, 0x70, 0x63, 0x4d, 0x54, 0x52,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x48, 0x6f, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x48, 0x6f, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x50, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x50, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x73, 0x54, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x49, 0x73, 0x54,
	0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x74, 0x74, 0x4d, 0x69, 0x63,
	0x72, 0x6f, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x52, 0x74, 0x74, 0x4d, 0x69,
	0x63, 0x72, 0x6f, 0x73, 0x22, 0x61, 0x0a, 0x0c, 0x4d, 0x54, 0x52, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x37, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x4d, 0x54, 0x52, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x32, 0xa1, 0x02, 0x0a, 0x09, 0x43, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x42, 0x0a, 0x0a, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x1d, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x15, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x48, 0x0a, 0x0d, 0x54, 0x63, 0x70,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x20, 0x2e, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x63, 0x70, 0x50,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x44, 0x0a, 0x0b, 0x46, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x12, 0x1e, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x46, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x15, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x40, 0x0a, 0x09, 0x4d, 0x74, 0x72,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1c, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x54, 0x52, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x09, 0x5a, 0x07, 0x2e,
	0x2f, 0x3b, 0x67, 0x6f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_collector_proto_rawDescOnce sync.Once
	file_proto_collector_proto_rawDescData = file_proto_collector_proto_rawDesc
)

func file_proto_collector_proto_rawDescGZIP() []byte {
	file_proto_collector_proto_rawDescOnce.Do(func() {
		file_proto_collector_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_collector_proto_rawDescData)
	})
	return file_proto_collector_proto_rawDescData
}

var file_proto_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_collector_proto_goTypes = []any{
	(*Empty)(nil),             // 0: collector_grpc.Empty
	(*GrpcPingResult)(nil),    // 1: collector_grpc.GrpcPingResult
	(*PingReportReq)(nil),     // 2: collector_grpc.PingReportReq
	(*GrpcTcpPingResult)(nil), // 3: collector_grpc.GrpcTcpPingResult
	(*TcpPingReportReq)(nil),  // 4: collector_grpc.TcpPingReportReq
	(*GrpcFPingResult)(nil),   // 5: collector_grpc.GrpcFPingResult
	(*FPingReportReq)(nil),    // 6: collector_grpc.FPingReportReq
	(*GrpcMTRResult)(nil),     // 7: collector_grpc.GrpcMTRResult
	(*MTRReportReq)(nil),      // 8: collector_grpc.MTRReportReq
}
var file_proto_collector_proto_depIdxs = []int32{
	1, // 0: collector_grpc.PingReportReq.Results:type_name -> collector_grpc.GrpcPingResult
	3, // 1: collector_grpc.TcpPingReportReq.Results:type_name -> collector_grpc.GrpcTcpPingResult
	5, // 2: collector_grpc.FPingReportReq.Results:type_name -> collector_grpc.GrpcFPingResult
	7, // 3: collector_grpc.MTRReportReq.Results:type_name -> collector_grpc.GrpcMTRResult
	2, // 4: collector_grpc.Collector.PingReport:input_type -> collector_grpc.PingReportReq
	4, // 5: collector_grpc.Collector.TcpPingReport:input_type -> collector_grpc.TcpPingReportReq
	6, // 6: collector_grpc.Collector.FpingReport:input_type -> collector_grpc.FPingReportReq
	8, // 7: collector_grpc.Collector.MtrReport:input_type -> collector_grpc.MTRReportReq
	0, // 8: collector_grpc.Collector.PingReport:output_type -> collector_grpc.Empty
	0, // 9: collector_grpc.Collector.TcpPingReport:output_type -> collector_grpc.Empty
	0, // 10: collector_grpc.Collector.FpingReport:output_type -> collector_grpc.Empty
	0, // 11: collector_grpc.Collector.MtrReport:output_type -> collector_grpc.Empty
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_collector_proto_init() }
func file_proto_collector_proto_init() {
	if File_proto_collector_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_collector_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_collector_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GrpcPingResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_collector_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*PingReportReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_collector_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GrpcTcpPingResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_collector_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*TcpPingReportReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_collector_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GrpcFPingResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_collector_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*FPingReportReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_collector_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GrpcMTRResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_collector_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*MTRReportReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_collector_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_collector_proto_goTypes,
		DependencyIndexes: file_proto_collector_proto_depIdxs,
		MessageInfos:      file_proto_collector_proto_msgTypes,
	}.Build()
	File_proto_collector_proto = out.File
	file_proto_collector_proto_rawDesc = nil
	file_proto_collector_proto_goTypes = nil
	file_proto_collector_proto_depIdxs = nil
}
