// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: proto/collector.proto

package gopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_collector_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{0}
}

type GrpcPingResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PingTaskUID uint64 `protobuf:"varint,1,opt,name=PingTaskUID,proto3" json:"PingTaskUID,omitempty"`
	IsTimeout   bool   `protobuf:"varint,2,opt,name=IsTimeout,proto3" json:"IsTimeout,omitempty"`
	RttMicros   uint32 `protobuf:"varint,3,opt,name=RttMicros,proto3" json:"RttMicros,omitempty"`
	SendAt      int64  `protobuf:"varint,4,opt,name=SendAt,proto3" json:"SendAt,omitempty"`
}

func (x *GrpcPingResult) Reset() {
	*x = GrpcPingResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_collector_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcPingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPingResult) ProtoMessage() {}

func (x *GrpcPingResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPingResult.ProtoReflect.Descriptor instead.
func (*GrpcPingResult) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{1}
}

func (x *GrpcPingResult) GetPingTaskUID() uint64 {
	if x != nil {
		return x.PingTaskUID
	}
	return 0
}

func (x *GrpcPingResult) GetIsTimeout() bool {
	if x != nil {
		return x.IsTimeout
	}
	return false
}

func (x *GrpcPingResult) GetRttMicros() uint32 {
	if x != nil {
		return x.RttMicros
	}
	return 0
}

func (x *GrpcPingResult) GetSendAt() int64 {
	if x != nil {
		return x.SendAt
	}
	return 0
}

type GrpcPingReportReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results  []*GrpcPingResult `protobuf:"bytes,1,rep,name=Results,proto3" json:"Results,omitempty"`
	AgentUID uint64            `protobuf:"varint,2,opt,name=AgentUID,proto3" json:"AgentUID,omitempty"`
}

func (x *GrpcPingReportReq) Reset() {
	*x = GrpcPingReportReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_collector_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcPingReportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPingReportReq) ProtoMessage() {}

func (x *GrpcPingReportReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPingReportReq.ProtoReflect.Descriptor instead.
func (*GrpcPingReportReq) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{2}
}

func (x *GrpcPingReportReq) GetResults() []*GrpcPingResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GrpcPingReportReq) GetAgentUID() uint64 {
	if x != nil {
		return x.AgentUID
	}
	return 0
}

type GrpcTcpPingResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TcpPingTaskUID uint64 `protobuf:"varint,1,opt,name=TcpPingTaskUID,proto3" json:"TcpPingTaskUID,omitempty"`
	IsTimeout      bool   `protobuf:"varint,2,opt,name=IsTimeout,proto3" json:"IsTimeout,omitempty"`
	RttMicros      uint32 `protobuf:"varint,3,opt,name=RttMicros,proto3" json:"RttMicros,omitempty"`
	SendAt         int64  `protobuf:"varint,4,opt,name=SendAt,proto3" json:"SendAt,omitempty"`
}

func (x *GrpcTcpPingResult) Reset() {
	*x = GrpcTcpPingResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_collector_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcTcpPingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcTcpPingResult) ProtoMessage() {}

func (x *GrpcTcpPingResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcTcpPingResult.ProtoReflect.Descriptor instead.
func (*GrpcTcpPingResult) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{3}
}

func (x *GrpcTcpPingResult) GetTcpPingTaskUID() uint64 {
	if x != nil {
		return x.TcpPingTaskUID
	}
	return 0
}

func (x *GrpcTcpPingResult) GetIsTimeout() bool {
	if x != nil {
		return x.IsTimeout
	}
	return false
}

func (x *GrpcTcpPingResult) GetRttMicros() uint32 {
	if x != nil {
		return x.RttMicros
	}
	return 0
}

func (x *GrpcTcpPingResult) GetSendAt() int64 {
	if x != nil {
		return x.SendAt
	}
	return 0
}

type GrpcTcpPingReportReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results  []*GrpcTcpPingResult `protobuf:"bytes,1,rep,name=Results,proto3" json:"Results,omitempty"`
	AgentUID uint64               `protobuf:"varint,2,opt,name=AgentUID,proto3" json:"AgentUID,omitempty"`
}

func (x *GrpcTcpPingReportReq) Reset() {
	*x = GrpcTcpPingReportReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_collector_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcTcpPingReportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcTcpPingReportReq) ProtoMessage() {}

func (x *GrpcTcpPingReportReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcTcpPingReportReq.ProtoReflect.Descriptor instead.
func (*GrpcTcpPingReportReq) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{4}
}

func (x *GrpcTcpPingReportReq) GetResults() []*GrpcTcpPingResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GrpcTcpPingReportReq) GetAgentUID() uint64 {
	if x != nil {
		return x.AgentUID
	}
	return 0
}

var File_proto_collector_proto protoreflect.FileDescriptor

var file_proto_collector_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x86, 0x01, 0x0a, 0x0e, 0x47, 0x72, 0x70, 0x63, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x73, 0x6b, 0x55,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x54, 0x61,
	0x73, 0x6b, 0x55, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x6f,
	0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x49, 0x73, 0x54, 0x69, 0x6d, 0x65,
	0x6f, 0x75, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x74, 0x74, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x52, 0x74, 0x74, 0x4d, 0x69, 0x63, 0x72, 0x6f,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x22, 0x69, 0x0a, 0x11, 0x47, 0x72, 0x70,
	0x63, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x38,
	0x0a, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x47, 0x72, 0x70, 0x63, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52,
	0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x55, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x55, 0x49, 0x44, 0x22, 0x8f, 0x01, 0x0a, 0x11, 0x47, 0x72, 0x70, 0x63, 0x54, 0x63, 0x70,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x54, 0x63,
	0x70, 0x50, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x73, 0x6b, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0e, 0x54, 0x63, 0x70, 0x50, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x73, 0x6b, 0x55,
	0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x49, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x52, 0x74, 0x74, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x52, 0x74, 0x74, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x53, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x22, 0x6f, 0x0a, 0x14, 0x47, 0x72, 0x70, 0x63, 0x54, 0x63,
	0x70, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x3b,
	0x0a, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x47, 0x72, 0x70, 0x63, 0x54, 0x63, 0x70, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x55, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x55, 0x49, 0x44, 0x32, 0xad, 0x01, 0x0a, 0x09, 0x43, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x4c, 0x0a, 0x10, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x50,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x21, 0x2e, 0x63, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x50,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x52, 0x0a, 0x13, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x63, 0x70,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x24, 0x2e, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x72, 0x70, 0x63,
	0x54, 0x63, 0x70, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x15, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x3b, 0x67, 0x6f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_collector_proto_rawDescOnce sync.Once
	file_proto_collector_proto_rawDescData = file_proto_collector_proto_rawDesc
)

func file_proto_collector_proto_rawDescGZIP() []byte {
	file_proto_collector_proto_rawDescOnce.Do(func() {
		file_proto_collector_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_collector_proto_rawDescData)
	})
	return file_proto_collector_proto_rawDescData
}

var file_proto_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_collector_proto_goTypes = []any{
	(*Empty)(nil),                // 0: collector_grpc.Empty
	(*GrpcPingResult)(nil),       // 1: collector_grpc.GrpcPingResult
	(*GrpcPingReportReq)(nil),    // 2: collector_grpc.GrpcPingReportReq
	(*GrpcTcpPingResult)(nil),    // 3: collector_grpc.GrpcTcpPingResult
	(*GrpcTcpPingReportReq)(nil), // 4: collector_grpc.GrpcTcpPingReportReq
}
var file_proto_collector_proto_depIdxs = []int32{
	1, // 0: collector_grpc.GrpcPingReportReq.Results:type_name -> collector_grpc.GrpcPingResult
	3, // 1: collector_grpc.GrpcTcpPingReportReq.Results:type_name -> collector_grpc.GrpcTcpPingResult
	2, // 2: collector_grpc.Collector.ReportPingResult:input_type -> collector_grpc.GrpcPingReportReq
	4, // 3: collector_grpc.Collector.ReportTcpPingResult:input_type -> collector_grpc.GrpcTcpPingReportReq
	0, // 4: collector_grpc.Collector.ReportPingResult:output_type -> collector_grpc.Empty
	0, // 5: collector_grpc.Collector.ReportTcpPingResult:output_type -> collector_grpc.Empty
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_collector_proto_init() }
func file_proto_collector_proto_init() {
	if File_proto_collector_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_collector_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_collector_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GrpcPingResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_collector_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GrpcPingReportReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_collector_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GrpcTcpPingResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_collector_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GrpcTcpPingReportReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_collector_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_collector_proto_goTypes,
		DependencyIndexes: file_proto_collector_proto_depIdxs,
		MessageInfos:      file_proto_collector_proto_msgTypes,
	}.Build()
	File_proto_collector_proto = out.File
	file_proto_collector_proto_rawDesc = nil
	file_proto_collector_proto_goTypes = nil
	file_proto_collector_proto_depIdxs = nil
}
