// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: proto/controller.proto

package gopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_Ping    CommandType = 0
	CommandType_TcpPing CommandType = 1
	CommandType_Fping   CommandType = 2
	CommandType_Mtr     CommandType = 3
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "Ping",
		1: "TcpPing",
		2: "Fping",
		3: "Mtr",
	}
	CommandType_value = map[string]int32{
		"Ping":    0,
		"TcpPing": 1,
		"Fping":   2,
		"Mtr":     3,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_controller_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_proto_controller_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{0}
}

type RegisterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentID uint32 `protobuf:"varint,1,opt,name=AgentID,proto3" json:"AgentID,omitempty"`
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_controller_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterReq) GetAgentID() uint32 {
	if x != nil {
		return x.AgentID
	}
	return 0
}

type UpdateCommandResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommandType CommandType `protobuf:"varint,1,opt,name=CommandType,proto3,enum=controller_grpc.CommandType" json:"CommandType,omitempty"`
	Version     string      `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
}

func (x *UpdateCommandResp) Reset() {
	*x = UpdateCommandResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_controller_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCommandResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommandResp) ProtoMessage() {}

func (x *UpdateCommandResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommandResp.ProtoReflect.Descriptor instead.
func (*UpdateCommandResp) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateCommandResp) GetCommandType() CommandType {
	if x != nil {
		return x.CommandType
	}
	return CommandType_Ping
}

func (x *UpdateCommandResp) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type CommandReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentID uint32 `protobuf:"varint,1,opt,name=AgentID,proto3" json:"AgentID,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
}

func (x *CommandReq) Reset() {
	*x = CommandReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_controller_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandReq) ProtoMessage() {}

func (x *CommandReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandReq.ProtoReflect.Descriptor instead.
func (*CommandReq) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{2}
}

func (x *CommandReq) GetAgentID() uint32 {
	if x != nil {
		return x.AgentID
	}
	return 0
}

func (x *CommandReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GrpcPingCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	IP         string `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	TimeoutMS  uint32 `protobuf:"varint,3,opt,name=TimeoutMS,proto3" json:"TimeoutMS,omitempty"`
	IntervalMS uint32 `protobuf:"varint,4,opt,name=IntervalMS,proto3" json:"IntervalMS,omitempty"`
	DSCP       uint32 `protobuf:"varint,5,opt,name=DSCP,proto3" json:"DSCP,omitempty"`
}

func (x *GrpcPingCommand) Reset() {
	*x = GrpcPingCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_controller_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcPingCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPingCommand) ProtoMessage() {}

func (x *GrpcPingCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPingCommand.ProtoReflect.Descriptor instead.
func (*GrpcPingCommand) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{3}
}

func (x *GrpcPingCommand) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *GrpcPingCommand) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *GrpcPingCommand) GetTimeoutMS() uint32 {
	if x != nil {
		return x.TimeoutMS
	}
	return 0
}

func (x *GrpcPingCommand) GetIntervalMS() uint32 {
	if x != nil {
		return x.IntervalMS
	}
	return 0
}

func (x *GrpcPingCommand) GetDSCP() uint32 {
	if x != nil {
		return x.DSCP
	}
	return 0
}

type GrpcFpingCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	IP        string `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	TimeoutMS uint32 `protobuf:"varint,3,opt,name=TimeoutMS,proto3" json:"TimeoutMS,omitempty"`
	DSCP      uint32 `protobuf:"varint,5,opt,name=DSCP,proto3" json:"DSCP,omitempty"`
}

func (x *GrpcFpingCommand) Reset() {
	*x = GrpcFpingCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_controller_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcFpingCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcFpingCommand) ProtoMessage() {}

func (x *GrpcFpingCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcFpingCommand.ProtoReflect.Descriptor instead.
func (*GrpcFpingCommand) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{4}
}

func (x *GrpcFpingCommand) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *GrpcFpingCommand) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *GrpcFpingCommand) GetTimeoutMS() uint32 {
	if x != nil {
		return x.TimeoutMS
	}
	return 0
}

func (x *GrpcFpingCommand) GetDSCP() uint32 {
	if x != nil {
		return x.DSCP
	}
	return 0
}

type PingCommandsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version      string             `protobuf:"bytes,1,opt,name=Version,proto3" json:"Version,omitempty"`
	PingCommands []*GrpcPingCommand `protobuf:"bytes,2,rep,name=PingCommands,proto3" json:"PingCommands,omitempty"`
}

func (x *PingCommandsResp) Reset() {
	*x = PingCommandsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_controller_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingCommandsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingCommandsResp) ProtoMessage() {}

func (x *PingCommandsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingCommandsResp.ProtoReflect.Descriptor instead.
func (*PingCommandsResp) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{5}
}

func (x *PingCommandsResp) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingCommandsResp) GetPingCommands() []*GrpcPingCommand {
	if x != nil {
		return x.PingCommands
	}
	return nil
}

type GrpcTcpPingCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Target     string `protobuf:"bytes,2,opt,name=Target,proto3" json:"Target,omitempty"`
	TimeoutMS  uint32 `protobuf:"varint,3,opt,name=TimeoutMS,proto3" json:"TimeoutMS,omitempty"`
	IntervalMS uint32 `protobuf:"varint,4,opt,name=IntervalMS,proto3" json:"IntervalMS,omitempty"`
}

func (x *GrpcTcpPingCommand) Reset() {
	*x = GrpcTcpPingCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_controller_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcTcpPingCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcTcpPingCommand) ProtoMessage() {}

func (x *GrpcTcpPingCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcTcpPingCommand.ProtoReflect.Descriptor instead.
func (*GrpcTcpPingCommand) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{6}
}

func (x *GrpcTcpPingCommand) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *GrpcTcpPingCommand) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *GrpcTcpPingCommand) GetTimeoutMS() uint32 {
	if x != nil {
		return x.TimeoutMS
	}
	return 0
}

func (x *GrpcTcpPingCommand) GetIntervalMS() uint32 {
	if x != nil {
		return x.IntervalMS
	}
	return 0
}

type TcpPingCommandResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version         string                `protobuf:"bytes,1,opt,name=Version,proto3" json:"Version,omitempty"`
	TcpPingCommands []*GrpcTcpPingCommand `protobuf:"bytes,2,rep,name=TcpPingCommands,proto3" json:"TcpPingCommands,omitempty"`
}

func (x *TcpPingCommandResp) Reset() {
	*x = TcpPingCommandResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_controller_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TcpPingCommandResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpPingCommandResp) ProtoMessage() {}

func (x *TcpPingCommandResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpPingCommandResp.ProtoReflect.Descriptor instead.
func (*TcpPingCommandResp) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{7}
}

func (x *TcpPingCommandResp) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TcpPingCommandResp) GetTcpPingCommands() []*GrpcTcpPingCommand {
	if x != nil {
		return x.TcpPingCommands
	}
	return nil
}

type FpingCommandResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version       string              `protobuf:"bytes,1,opt,name=Version,proto3" json:"Version,omitempty"`
	FpingCommands []*GrpcFpingCommand `protobuf:"bytes,2,rep,name=FpingCommands,proto3" json:"FpingCommands,omitempty"`
}

func (x *FpingCommandResp) Reset() {
	*x = FpingCommandResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_controller_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FpingCommandResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FpingCommandResp) ProtoMessage() {}

func (x *FpingCommandResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FpingCommandResp.ProtoReflect.Descriptor instead.
func (*FpingCommandResp) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{8}
}

func (x *FpingCommandResp) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *FpingCommandResp) GetFpingCommands() []*GrpcFpingCommand {
	if x != nil {
		return x.FpingCommands
	}
	return nil
}

type MtrCommandResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version   string `protobuf:"bytes,1,opt,name=Version,proto3" json:"Version,omitempty"`
	IP        string `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	Times     uint32 `protobuf:"varint,3,opt,name=Times,proto3" json:"Times,omitempty"`
	HopLimit  uint32 `protobuf:"varint,4,opt,name=HopLimit,proto3" json:"HopLimit,omitempty"`
	TimeoutMS uint32 `protobuf:"varint,5,opt,name=TimeoutMS,proto3" json:"TimeoutMS,omitempty"`
}

func (x *MtrCommandResp) Reset() {
	*x = MtrCommandResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_controller_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MtrCommandResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MtrCommandResp) ProtoMessage() {}

func (x *MtrCommandResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MtrCommandResp.ProtoReflect.Descriptor instead.
func (*MtrCommandResp) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{9}
}

func (x *MtrCommandResp) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MtrCommandResp) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *MtrCommandResp) GetTimes() uint32 {
	if x != nil {
		return x.Times
	}
	return 0
}

func (x *MtrCommandResp) GetHopLimit() uint32 {
	if x != nil {
		return x.HopLimit
	}
	return 0
}

func (x *MtrCommandResp) GetTimeoutMS() uint32 {
	if x != nil {
		return x.TimeoutMS
	}
	return 0
}

var File_proto_controller_proto protoreflect.FileDescriptor

var file_proto_controller_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x22, 0x27, 0x0a, 0x0b, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x49, 0x44, 0x22, 0x6d, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3e, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0x40, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12,
	0x18, 0x0a, 0x07, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x22, 0x83, 0x01, 0x0a, 0x0f, 0x47, 0x72, 0x70, 0x63, 0x50, 0x69, 0x6e, 0x67,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x50, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x50, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x6f,
	0x75, 0x74, 0x4d, 0x53, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65,
	0x6f, 0x75, 0x74, 0x4d, 0x53, 0x12, 0x1e, 0x0a, 0x0a, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61,
	0x6c, 0x4d, 0x53, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x76, 0x61, 0x6c, 0x4d, 0x53, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x53, 0x43, 0x50, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x44, 0x53, 0x43, 0x50, 0x22, 0x64, 0x0a, 0x10, 0x47, 0x72, 0x70,
	0x63, 0x46, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x50, 0x12, 0x1c, 0x0a,
	0x09, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x4d, 0x53, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x4d, 0x53, 0x12, 0x12, 0x0a, 0x04, 0x44,
	0x53, 0x43, 0x50, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x44, 0x53, 0x43, 0x50, 0x22,
	0x72, 0x0a, 0x10, 0x50, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x44, 0x0a,
	0x0c, 0x50, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72,
	0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x50, 0x69, 0x6e, 0x67, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x73, 0x22, 0x7a, 0x0a, 0x12, 0x47, 0x72, 0x70, 0x63, 0x54, 0x63, 0x70, 0x50, 0x69,
	0x6e, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x4d, 0x53, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x4d, 0x53, 0x12,
	0x1e, 0x0a, 0x0a, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x4d, 0x53, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0a, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x4d, 0x53, 0x22,
	0x7d, 0x0a, 0x12, 0x54, 0x63, 0x70, 0x50, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x4d, 0x0a, 0x0f, 0x54, 0x63, 0x70, 0x50, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x54,
	0x63, 0x70, 0x50, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x0f, 0x54,
	0x63, 0x70, 0x50, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x22, 0x75,
	0x0a, 0x10, 0x46, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x47, 0x0a, 0x0d,
	0x46, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72,
	0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x46, 0x70, 0x69, 0x6e, 0x67, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x0d, 0x46, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x73, 0x22, 0x8a, 0x01, 0x0a, 0x0e, 0x4d, 0x74, 0x72, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x49, 0x50, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x48, 0x6f, 0x70, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x48, 0x6f, 0x70, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x4d,
	0x53, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x4d, 0x53, 0x2a, 0x38, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x54,
	0x63, 0x70, 0x50, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x70, 0x69, 0x6e,
	0x67, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x74, 0x72, 0x10, 0x03, 0x32, 0xa7, 0x03, 0x0a,
	0x0a, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x4e, 0x0a, 0x08, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1c, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c,
	0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x30, 0x01, 0x12, 0x55, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x54, 0x63, 0x70, 0x50, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x12, 0x1b, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x54, 0x63, 0x70, 0x50, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x50, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1b, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65,
	0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65,
	0x71, 0x1a, 0x21, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x51, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x46, 0x70, 0x69, 0x6e, 0x67,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1b, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65,
	0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x46, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4d, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4d, 0x74,
	0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1b, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c,
	0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x74, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x3b, 0x67, 0x6f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_controller_proto_rawDescOnce sync.Once
	file_proto_controller_proto_rawDescData = file_proto_controller_proto_rawDesc
)

func file_proto_controller_proto_rawDescGZIP() []byte {
	file_proto_controller_proto_rawDescOnce.Do(func() {
		file_proto_controller_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_controller_proto_rawDescData)
	})
	return file_proto_controller_proto_rawDescData
}

var file_proto_controller_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_controller_proto_goTypes = []any{
	(CommandType)(0),           // 0: controller_grpc.CommandType
	(*RegisterReq)(nil),        // 1: controller_grpc.RegisterReq
	(*UpdateCommandResp)(nil),  // 2: controller_grpc.UpdateCommandResp
	(*CommandReq)(nil),         // 3: controller_grpc.CommandReq
	(*GrpcPingCommand)(nil),    // 4: controller_grpc.GrpcPingCommand
	(*GrpcFpingCommand)(nil),   // 5: controller_grpc.GrpcFpingCommand
	(*PingCommandsResp)(nil),   // 6: controller_grpc.PingCommandsResp
	(*GrpcTcpPingCommand)(nil), // 7: controller_grpc.GrpcTcpPingCommand
	(*TcpPingCommandResp)(nil), // 8: controller_grpc.TcpPingCommandResp
	(*FpingCommandResp)(nil),   // 9: controller_grpc.FpingCommandResp
	(*MtrCommandResp)(nil),     // 10: controller_grpc.MtrCommandResp
}
var file_proto_controller_proto_depIdxs = []int32{
	0,  // 0: controller_grpc.UpdateCommandResp.CommandType:type_name -> controller_grpc.CommandType
	4,  // 1: controller_grpc.PingCommandsResp.PingCommands:type_name -> controller_grpc.GrpcPingCommand
	7,  // 2: controller_grpc.TcpPingCommandResp.TcpPingCommands:type_name -> controller_grpc.GrpcTcpPingCommand
	5,  // 3: controller_grpc.FpingCommandResp.FpingCommands:type_name -> controller_grpc.GrpcFpingCommand
	1,  // 4: controller_grpc.Controller.Register:input_type -> controller_grpc.RegisterReq
	3,  // 5: controller_grpc.Controller.GetTcpPingCommand:input_type -> controller_grpc.CommandReq
	3,  // 6: controller_grpc.Controller.GetPingCommand:input_type -> controller_grpc.CommandReq
	3,  // 7: controller_grpc.Controller.GetFpingCommand:input_type -> controller_grpc.CommandReq
	3,  // 8: controller_grpc.Controller.GetMtrCommand:input_type -> controller_grpc.CommandReq
	2,  // 9: controller_grpc.Controller.Register:output_type -> controller_grpc.UpdateCommandResp
	8,  // 10: controller_grpc.Controller.GetTcpPingCommand:output_type -> controller_grpc.TcpPingCommandResp
	6,  // 11: controller_grpc.Controller.GetPingCommand:output_type -> controller_grpc.PingCommandsResp
	9,  // 12: controller_grpc.Controller.GetFpingCommand:output_type -> controller_grpc.FpingCommandResp
	10, // 13: controller_grpc.Controller.GetMtrCommand:output_type -> controller_grpc.MtrCommandResp
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_controller_proto_init() }
func file_proto_controller_proto_init() {
	if File_proto_controller_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_controller_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RegisterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_controller_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateCommandResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_controller_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CommandReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_controller_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GrpcPingCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_controller_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GrpcFpingCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_controller_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*PingCommandsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_controller_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GrpcTcpPingCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_controller_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*TcpPingCommandResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_controller_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*FpingCommandResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_controller_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*MtrCommandResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_controller_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_controller_proto_goTypes,
		DependencyIndexes: file_proto_controller_proto_depIdxs,
		EnumInfos:         file_proto_controller_proto_enumTypes,
		MessageInfos:      file_proto_controller_proto_msgTypes,
	}.Build()
	File_proto_controller_proto = out.File
	file_proto_controller_proto_rawDesc = nil
	file_proto_controller_proto_goTypes = nil
	file_proto_controller_proto_depIdxs = nil
}
